### ISSUE TITLE
[OTHER] Short url to contact google form

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Pradumnasaraf.github.io#6] opened 2022-02-22 13:58 UTC
### What would you like to share?

rn the link for the google form (contact) is a huge url, you can go to settings and make it smaller.

If you don't know how to do this, I requested access to the google form, will do the needful and then you can remove access, will also try and fix the issue that your not getting emails when the form gets new responses.

**Comment by Pradumnasaraf** [comment] 2022-02-22 14:20
Hey! shortening the URL doesn't change the functionality, also we will soon remove the google (and the problem is fixed now :))

Thank you for the effort and opening issue

**Closed by Pradumnasaraf** 2022-02-22 14:20 UTC

**Comment by Pradumnasaraf** [comment] 2022-02-22 14:25
> > Hey! shortening the URL doesn't change the functionality, also we will soon remove the google (and the problem is fixed now :))
> > Thank you for the effort and opening issue
> 
> Yeah true, just when I opened the link a LONG link showed up in the taskbar, but yeah no harm... Just curious, are you shifting to my suggestion [FormSubmit](https://formsubmit.co/)?

Didn't finalize it yet, but thinking of some backend solution. thank you for your suggestions :)

**Comment by KendallDoesCoding** [comment] 2022-02-22 14:39
Yep.. It's your decision, I was just wondering!
